# - Try to find wangle
# This will define
# WANGLE_FOUND
# WANGLE_INCLUDE_DIR
# WANGLE_LIBRARIES

CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7 FATAL_ERROR)

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(WANGLE_LIBRARY wangle PATHS ${WANGLE_LIBRARYDIR})
FIND_PATH(WANGLE_INCLUDE_DIR "wangle/acceptor/Acceptor.h" PATHS ${WANGLE_INCLUDEDIR})

SET(WANGLE_LIBRARIES ${WANGLE_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Wangle
  REQUIRED_ARGS WANGLE_INCLUDE_DIR WANGLE_LIBRARIES)
